# Generated by Django 5.0.7 on 2024-08-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_doctor_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.PositiveIntegerField(null=True)),
                ('patientName', models.CharField(max_length=40)),
                ('assignedDoctorName', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('symptoms', models.CharField(max_length=100, null=True)),
                ('admitDate', models.DateField()),
                ('todayDate', models.DateField()),
                ('BloodGroup', models.CharField(max_length=10)),
                ('PostPrandialBloodSugar', models.CharField(max_length=20)),
                ('FastingBloodReport', models.CharField(max_length=20)),
                ('Cholestrol', models.CharField(max_length=20)),
                ('LDLCholestrol', models.CharField(max_length=20)),
                ('HDLCholestrol', models.CharField(max_length=20)),
                ('VitaminD3', models.CharField(max_length=20)),
                ('Alergies', models.CharField(max_length=20)),
                ('OtherReports', models.CharField(max_length=20)),
            ],
        ),
    ]
