# Generated by Django 5.0.7 on 2024-08-29 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lipid_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cholestrol', models.CharField(max_length=40)),
                ('Triglyceride', models.CharField(max_length=40)),
                ('Hdl_cholestrol', models.CharField(max_length=40)),
                ('Ldl_cholestrol', models.CharField(max_length=40)),
                ('VLDL', models.CharField(max_length=40)),
                ('CHOL_HDL_ratio', models.CharField(max_length=40)),
                ('LDL_HDL_ratio', models.CharField(max_length=40)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
    ]
