# Generated by Django 5.0.7 on 2024-08-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_lipid_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lipid_Profile',
            new_name='LipidProfile',
        ),
    ]
