# Generated by Django 5.0.7 on 2024-08-30 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_rename_lipid_profile_lipidprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipidprofile',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='admitDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='assignedDoctorName',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='patientId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='symptoms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lipidprofile',
            name='todayDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
