# Generated by Django 5.0.7 on 2024-08-30 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_fbs_reports_ppbs_reports'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbs_reports',
            old_name='PostPrandialBloodSugar',
            new_name='FastingBloodSugar',
        ),
        migrations.RenameField(
            model_name='ppbs_reports',
            old_name='VitaminD12',
            new_name='PostPrandialBloodSugar',
        ),
        migrations.RenameField(
            model_name='vitamin_reports',
            old_name='FastingBloodSugar',
            new_name='VitaminD12',
        ),
        migrations.RemoveField(
            model_name='ppbs_reports',
            name='VitaminD3',
        ),
        migrations.AddField(
            model_name='vitamin_reports',
            name='VitaminD3',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
